CMS/CMS/Areas/Admin/Controllers/ManagerOrderController.cs
using System;
using System.Data;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CMS.Model;
using CMS.Dao;
using CMS.Lib;
using CMS.Common.StringProcess;
using Excel = Microsoft.Office.Interop.Excel;
using System.Runtime.InteropServices;

namespace CMS.Areas.Admin.Controllers
{
    public class ManagerOrderController : BaseController
    {
        //
        // GET: /Admin/ManagerOrder/

        public ActionResult Index(string id)
        {
            string page = "1";
            const int pageSize = 50;
            ViewBag.PageSize = pageSize;
            page = id;
            ViewBag.Page = page;
            OrderDao logic = new OrderDao();
            List<Order_GetByPage_Result> model = new List<Order_GetByPage_Result>();
            model = logic.Order_GetByPage(0, Convert.ToInt32(page), pageSize);
            ViewBag.PanelTitle = ViewBag.Title = "Danh sách đơn hàng";
            return View("Index", model);
        }

        public ActionResult Search(string id)
        {
            string page = "1";
            const int pageSize = 50;
            string key = "";//Không tìm kiếm theo key
            DateTime dStart = new DateTime(1900, 01, 01, 01, 01, 01);
            DateTime dEnd = new DateTime(2100, 12, 31, 23, 59, 59);

            string[] list = id.Split('-');
            page = list[3];
            if (list[0].ToLower() != "null") { key = list[0]; }
            if (list[1].ToLower() != "null")
            {
                string[] listdStart = list[1].Split('_');
                dStart = new DateTime(Convert.ToInt32(listdStart[2]), Convert.ToInt32(listdStart[1]), Convert.ToInt32(listdStart[0]), 01, 01, 01);
            }
            if (list[2].ToLower() != "null")
            {
                string[] listdEnd = list[2].Split('_');
                dEnd = new DateTime(Convert.ToInt32(listdEnd[2]), Convert.ToInt32(listdEnd[1]), Convert.ToInt32(listdEnd[0]), 23, 59, 59);
            }

            ViewBag.Key = list[0];
            ViewBag.dStart = list[1];
            ViewBag.dEnd = list[2];
            ViewBag.Page = page;
            ViewBag.PageSize = pageSize;

            int orderSuccess = 0;
            double priceSuccess = 0;

            OrderDao logic = new OrderDao();
            List<Order> model = new List<Order>();
            List<Order> results = new List<Order>();
            model = logic.OrderSearch(key, dStart, dEnd);
            int rowStart = 0;
            int rowEnd = 0;
            if (model != null && model.Count > 0)
            {
                rowStart = (Convert.ToInt32(page) - 1) * Convert.ToInt32(pageSize);
                rowEnd = (rowStart + Convert.ToInt32(pageSize)) > model.Count ? model.Count : rowStart + Convert.ToInt32(pageSize);
                for (int i = rowStart; i < rowEnd; i++)
                {
                    #region Add item
                    Order item = new Order();
                    item = model[i];
                    results.Add(item);
                    #endregion
                }
                foreach(var item in model)
                {
                    if (item.Status == CMS.Common.Keywords.DataStatus.Success)
                    {
                        orderSuccess++;
                        priceSuccess = priceSuccess + item.TotalPayment.Value;
                    }
                }
            }
            ViewBag.TotalCount = String.Format("{0:n0}", model.Count);
            ViewBag.OrderSuccess = String.Format("{0:n0}", orderSuccess);
            ViewBag.PriceSuccess = String.Format("{0:n0}", priceSuccess);
            ViewBag.PanelTitle = ViewBag.Title = String.Format("Tìm kiếm nâng cao: ({0} đơn hàng)", String.Format("{0:n0}", model.Count));
            ViewBag.ControllersName = "ManagerOrderSearch";
            return View("Search", model);
        }

        [HttpGet]
        public FileContentResult ExportToExcel(string id)
        {
            LoginAccountDao LoginAccountLogic = new LoginAccountDao();
            string key = "";//Không tìm kiếm theo key
            DateTime dStart = new DateTime(1900, 01, 01, 01, 01, 01);
            DateTime dEnd = new DateTime(2100, 12, 31, 23, 59, 59);

            string[] list = id.Split('-');
            if (list[0].ToLower() != "null") { key = list[0]; }
            if (list[1].ToLower() != "null")
            {
                string[] listdStart = list[1].Split('_');
                dStart = new DateTime(Convert.ToInt32(listdStart[2]), Convert.ToInt32(listdStart[1]), Convert.ToInt32(listdStart[0]), 01, 01, 01);
            }
            if (list[2].ToLower() != "null")
            {
                string[] listdEnd = list[2].Split('_');
                dEnd = new DateTime(Convert.ToInt32(listdEnd[2]), Convert.ToInt32(listdEnd[1]), Convert.ToInt32(listdEnd[0]), 23, 59, 59);
            }

            ViewBag.Key = list[0];
            ViewBag.dStart = list[1];
            ViewBag.dEnd = list[2];

            OrderDao logic = new OrderDao();
            List<Order> model = new List<Order>();
            model = logic.OrderSearch(key, dStart, dEnd);

            #region Add table
            DataTable dt = new DataTable();
            dt.Columns.Add("DateTimeCreate", typeof(string));
            dt.Columns.Add("TotalTime", typeof(string));
            dt.Columns.Add("Name", typeof(string));
            dt.Columns.Add("Mobile", typeof(string));
            dt.Columns.Add("TotalPrice", typeof(string));
            dt.Columns.Add("Note", typeof(string));
            dt.Columns.Add("LoginAccountCheckin", typeof(string));
            dt.Columns.Add("LoginAccountCheckout", typeof(string));

            if (model != null && model.Count > 0)
            {
                foreach (var item in model)
                {
                    string DateTimeCreate = "";
                    string TotalTime = "-----";
                    string Name = "";
                    string Mobile = "";
                    string TotalPrice = "";
                    string Note = "";
                    string LoginAccountCheckin = "";
                    string LoginAccountCheckout = "";

                    string DateTimeDay = "";
                    if (item.DateTimeCreate != null)
                    {
                        DateTimeDay = item.DateTimeCreate.Value.ToString("dd/MM/yyyy");
                    }
                    string DateTimeStart = "-----";
                    if (item.DateTimeStart != null)
                    {
                        DateTimeStart = item.DateTimeStart.Value.ToString("HH:mm");
                    }
                    string DateTimeEnd = "-----";
                    if (item.DateTimeEnd != null)
                    {
                        DateTimeEnd = item.DateTimeEnd.Value.ToString("HH:mm");
                    }
                    DateTimeCreate = String.Format("Từ {0} đến {1} ngày {2}", DateTimeStart, DateTimeEnd, DateTimeDay);

                    if (item.DateTimeEnd != null && item.DateTimeStart != null)
                    {
                        int totalminute = (item.DateTimeEnd.Value.Hour * 60 + item.DateTimeEnd.Value.Minute) - (item.DateTimeStart.Value.Hour * 60 + item.DateTimeStart.Value.Minute);
                        TotalTime = String.Format("{0} giờ {1} phút", totalminute / 60, totalminute % 60);
                    }
                    Name = item.Name;
                    Mobile = item.Mobile;
                    Note = item.Note;
                    TotalPrice = String.Format("{0:n0}", item.TotalPayment.Value);
                    if (item.LoginAccountCheckin.Value != 0 && item.LoginAccountCheckin != null)
                    {
                        LoginAccountCheckin = (LoginAccountLogic.LoginAccount_ViewDetail(item.LoginAccountCheckin.Value)).FullName;
                    }
                    if (item.LoginAccountCheckout.Value != 0 && item.LoginAccountCheckout != null)
                    {
                        LoginAccountCheckout = (LoginAccountLogic.LoginAccount_ViewDetail(item.LoginAccountCheckout.Value)).FullName;
                    }
                    dt.Rows.Add(DateTimeCreate, TotalTime, Name, Mobile, TotalPrice, Note, LoginAccountCheckin, LoginAccountCheckout);
                }
            }
            else
            {
                dt.Rows.Add("", "", "", "", "", "", "","");
            }
            #endregion

            string fileName = String.Format("Report_{0}.xlsx", DateTime.Now.ToString("yyyyMMddHHmmss"));
            string[] columns = { "DateTimeCreate","TotalTime", "Name", "Mobile", "TotalPrice", "Note", "LoginAccountCheckin", "LoginAccountCheckout" };
            string columnsName = "Ngày|Tổng thời gian|Khách hàng|Số điện thoại|Tổng tiền|Ghi chú|Nhân viên check in|Nhân viên check out";
            byte[] filecontent = CMS.Common.Utility.ExcelExportHelper.ExportExcel(dt, "Báo cáo bán hàng", true, columnsName, columns);
            return File(filecontent, CMS.Common.Utility.ExcelExportHelper.ExcelContentType, fileName);
        }

        public JsonResult CheckTime(string id, string hoursStart, string minuteStart, string hoursEnd, string minuteEnd)
        {
            try
            {
                #region Tính tổng thời gian
                double totalminute = 0;
                OrderDao OrderLogic = new OrderDao();
                Order itemOrder = new Order();
                itemOrder = OrderLogic.Orders_ViewDetail(Convert.ToInt32(id));
                DateTime DateTimeStart = new DateTime(itemOrder.DateTimeStart.Value.Year, itemOrder.DateTimeStart.Value.Month, itemOrder.DateTimeStart.Value.Day, Convert.ToInt32(hoursStart), Convert.ToInt32(minuteStart), 0);
                DateTime DateTimeEnd = new DateTime(DateTime.Now.Year, DateTime.Now.Month, DateTime.Now.Day, Convert.ToInt32(hoursEnd), Convert.ToInt32(minuteEnd), 0);
                TimeSpan ts = new TimeSpan();

CMS/CMS/Areas/Admin/Views/ManagerOrder/Create.cshtml
@model CMS.Model.Order
@{
    Layout = "~/Areas/Admin/Views/Shared/_Layouts.cshtml";
}
<div class="card">
    <div class="card-body">
        @using (Html.BeginForm("Create", "ManagerOrder", FormMethod.Post))
        {
            @Html.AntiForgeryToken()
            @Html.ValidationSummary(true)
            <div class="col-sm-5 col-xs-12 form-control-span">
                <div class="col-sm-12 form-control-span-main">
                    <div class="form-group mt-3">
                        <label class="control-label">
                            Thời gian bắt đầu
                        </label>
                        <div class="controls">
                            @{
                                int minute = DateTime.Now.Minute;
                                int hour = DateTime.Now.Hour;
                                <select class="form-control" id="HoursStart" name="HoursStart" style="width: 48%; height: 36px; float: left; border-color: #d3d5d7;margin-right: 5px;">
                                    @for (int i = 1; i <= 24; i++)
                                    {
                                        <option value="@i" @(hour == i ? "selected" : "")>@i giờ </option>
                                    }
                                </select>
                                <select class="form-control" id="MinuteStart" name="MinuteStart" style="width: 48%; height: 36px; float: left; border-color: #d3d5d7; ">
                                    @for (int i = 0; i <= 60; i++)
                                    {
                                        <option value="@i" @(minute == i ? "selected" : "")>@i phút </option>
                                    }
                                </select>
                            }
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-sm-7 col-xs-12 form-control-span">
                <div class="col-sm-12 form-control-span-main">
                    <div class="form-group mt-3">
                        <label class="control-label">
                            Khách hàng
                            <span class="help-inline " style="color:red;">*</span>
                        </label>
                        <div class="controls">
                            @Html.TextBoxFor(model => model.Name, new { @class = "form-control", @placeholder = "", @autofocus = "autofocus" })
                        </div>
                    </div>
                    <div class="form-group mt-3">
                        <label class="control-label">
                            Số điện thoại
                        </label>
                        <div class="controls">
                            @Html.TextBoxFor(model => model.Mobile, new { @class = "form-control", @placeholder = "", @autofocus = "autofocus" })
                        </div>
                    </div>
                    <div class="form-group mt-3">
                        <label class="control-label">
                            Ghi chú
                        </label>
                        <div class="controls">
                            @Html.TextAreaFor(model => model.Note, new { @class = "form-control", @placeholder = "", @autofocus = "autofocus", style = "height:100px;" })
                        </div>
                    </div>
                </div>
            </div>
            <div class="form-actions no-margin">
                <a href="/Admin/ManagerOrder/Index/1" class="btn btn-secondary btn-sm">Hủy</a>
                <button type="submit" class="btn btn-success btn-sm text-white">Thêm mới</button>
            </div>
        }
        <div class="clearfix">
        </div>
    </div>
</div>

CMS/CMS/Areas/Admin/Views/ManagerOrder/Details.cshtml
@model CMS.Model.Order
@using CMS.Model
@using CMS.Dao
@{
    Layout = "~/Areas/Admin/Views/Shared/_Layouts.cshtml";
}
<div class="card">
    <div class="card-body">
        @using (Html.BeginForm("Edit", "ManagerOrder", FormMethod.Post))
        {
            @Html.AntiForgeryToken()
            @Html.ValidationSummary(true)
            <div class="col-sm-5 col-xs-12 form-control-span">
                <div class="col-sm-12 form-control-span-main">
                    <div class="form-group mt-3" style="width:100%;float:left;">
                        <label class="control-label">
                            @switch (Model.Id.ToString().Length)
                            {
                                case 1:
                                    <span style="font-weight:bold;margin:0px;">Mã đơn hàng: HĐ000@(Model.Id)</span>
                                    break;
                                case 2:
                                    <span style="font-weight:bold;margin:0px;">Mã đơn hàng: HĐ00@(Model.Id)</span>
                                    break;
                                case 3:
                                    <span style="font-weight:bold;margin:0px;">Mã đơn hàng: HĐ0@(Model.Id)</span>
                                    break;
                                default:
                                    <span style="font-weight:bold;margin:0px;">Mã đơn hàng: HĐ@(Model.Id)</span>
                                    break;
                            }
                        </label>
                        <div class="controls">
                            <p>
                                Ngày @Convert.ToDateTime(Model.DateTimeStart).ToString("dd/MM/yyyy")
                                @if (Model.Status == CMS.Common.Keywords.DataStatus.Deleted)
                                {
                                    <span class="badge bg-danger">Đã hủy</span>
                                }
                                else if (Model.Status == CMS.Common.Keywords.DataStatus.Success)
                                {
                                    <span class="badge bg-success">Đã thanh toán</span>
                                }
                                else
                                {
                                    <span class="badge bg-primary">Đang câu</span>
                                }
                            </p>
                        </div>
                    </div>
                    <div class="form-group mt-3" style="width: 100%; float: left; margin-top: 0px !important;">
                        <label class="control-label">
                            Thời gian bắt đầu
                        </label>
                        <div class="controls">
                            @{
                                int minute = Model.DateTimeStart.Value.Minute;
                                int hour = Model.DateTimeStart.Value.Hour;
                                <select class="form-control" id="HoursStart" name="HoursStart" onchange="CheckTime()" disabled style="width: 48%; height: 36px; float: left; border-color: #d3d5d7;margin-right: 5px;border-color:#00aa1e;">
                                    @for (int i = 1; i <= 24; i++)
                                    {
                                        <option value="@i" @(hour == i ? "selected" : "")>@i giờ </option>
                                    }
                                </select>
                                <select class="form-control" id="MinuteStart" name="MinuteStart" onchange="CheckTime()" disabled style="width: 48%; height: 36px; float: left; border-color: #d3d5d7; border-color: #00aa1e;">
                                    @for (int i = 0; i <= 60; i++)
                                    {
                                        <option value="@i" @(minute == i ? "selected" : "")>@i phút </option>
                                    }
                                </select>
                            }
                        </div>
                    </div>
                    <div class="form-group mt-3" style="width: 100%; float: left; margin-top: 0px !important;">
                        <label class="control-label">
                            Thời gian kết thúc
                        </label>
                        <div class="controls">
                            @{

                                int minuteEnd = 0;
                                int hourEnd = 0;
                                if (Model.DateTimeEnd != null)
                                {
                                    minuteEnd = Model.DateTimeEnd.Value.Minute;
                                    hourEnd = Model.DateTimeEnd.Value.Hour;
                                }
                                else
                                {
                                    minuteEnd = DateTime.Now.Minute;
                                    hourEnd = DateTime.Now.Hour;
                                }
                                <select class="form-control" id="HoursEnd" name="HoursEnd" onchange="CheckTime()" disabled style="width: 48%; height: 36px; float: left; border-color: #d3d5d7; margin-right: 5px; border-color: #eb0505;">
                                    @for (int i = 1; i <= 24; i++)
                                    {
                                        <option value="@i" @(hourEnd == i ? "selected" : "")>@i giờ </option>
                                    }
                                </select>
                                <select class="form-control" id="MinuteEnd" name="MinuteEnd" onchange="CheckTime()" disabled style="width: 48%; height: 36px; float: left; border-color: #d3d5d7; border-color: #eb0505;">
                                    @for (int i = 0; i <= 60; i++)
                                    {
                                        <option value="@i" @(minuteEnd == i ? "selected" : "")>@i phút </option>
                                    }
                                </select>
                            }
                        </div>
                    </div>
                    <div class="form-group mt-3" style="width: 100%; float: left; margin-top: 0px !important;">
                        <label class="control-label">
                            Tổng thời gian
                            @{
                                TimeSpan ts = new TimeSpan();
                                if (Model.DateTimeEnd != null)
                                {
                                    ts = Model.DateTimeEnd.Value.Subtract(Model.DateTimeStart.Value);
                                }
                                else
                                {
                                    ts = DateTime.Now.Subtract(Model.DateTimeStart.Value);
                                }
                                double totalminute = 0;
                                totalminute = Math.Round(ts.TotalMinutes, 0);
                                if (totalminute < 0) { totalminute = 0; }
                                if (Model.DateTimeEnd != null)
                                {
                                    <span id="pTime">@((int)totalminute / 60) giờ @((int)totalminute % 60) phút</span>
                                }
                                else
                                {
                                    <span id="pTime">-----</span>
                                }
                            }
                        </label>
                        <div class="controls">
                            Phí tạm tính: 
                            @{
                                if (totalminute < 0) { totalminute = 0; }
                                PriceBoardDao logic = new PriceBoardDao();
                                List<PriceBoard> list = new List<PriceBoard>();
                                list = logic.PriceBoardSearch(CMS.Common.Keywords.DataStatus.Display, totalminute);
                                if (Model.Status == CMS.Common.Keywords.DataStatus.Display)
                                {
                                    if (list.Count > 0)
                                    {
                                        <span>@(String.Format("{0:0,0}", list[0].Price))</span>
                                    }
                                    else
                                    {
                                        <span>@(String.Format("{0:0,0}", Model.TotalPayment))</span>
                                    }
                                }
                                else
                                {
                                    <span>@(String.Format("{0:0,0}", Model.TotalPayment))</span>
                                }
                            }
                        </div>
                    </div>
                    <div class="form-group mt-3" style="width: 100%; float: left; margin-top: 0px !important;">
                        <label class="control-label">
                            Tiền câu
                        </label>
                        <div class="controls">
                            <input autofocus="autofocus" class="form-control" id="TotalPayment" name="TotalPayment" placeholder="" disabled type="number" min="0" value="@Model.TotalPayment">
                        </div>
                    </div>
                    <div class="form-group mt-3" style="width: 100%; float: left; margin-top: 0px !important;">
                        <label class="control-label">
                            Phí dịch vụ
                        </label>
                        <div class="controls">
                            <input autofocus="autofocus" class="form-control" id="TotalPayment" name="TotalPayment" placeholder="" disabled type="number" min="0" value="@Model.Promotion">
                        </div>
                    </div>
                    <div class="form-group mt-3" style="width: 100%; float: left; margin-top: 0px !important;">
                        @if (Model.Status == CMS.Common.Keywords.DataStatus.Deleted)
                        {
                            <label class="control-label badge bg-danger" id="TotalPrice" style="float:left;width:100%;padding:10px;font-size:14px;">
                                Thanh toán: @(String.Format("{0:0,0}", (Model.Promotion + Model.TotalPayment))) đ
                            </label>
                        }
                        else if (Model.Status == CMS.Common.Keywords.DataStatus.Success)
                        {
                            <label class="control-label badge bg-success" id="TotalPrice" style="float:left;width:100%;padding:10px;font-size:14px;">
                                Thanh toán: @(String.Format("{0:0,0}", (Model.Promotion + Model.TotalPayment))) đ
                            </label>
                        }
                        else
                        {
                            <label class="control-label badge bg-primary" id="TotalPrice" style="float:left;width:100%;padding:10px;font-size:14px;">
                                Thanh toán: @(String.Format("{0:0,0}", (Model.TotalPrice))) đ
                            </label>
                        }
                        <div class="controls">

                        </div>
                    </div>
                </div>
            </div>
            <div class="col-sm-7 col-xs-12 form-control-span">
                <div class="col-sm-12 form-control-span-main">
                    <div class="form-group mt-3">
                        <label class="control-label">
                            Khách hàng
                            <span class="help-inline " style="color:red;">*</span>
                        </label>
                        <div class="controls">
                            @Html.TextBoxFor(model => model.Name, new { @class = "form-control", @placeholder = "", @autofocus = "autofocus", disabled = "disabled" })
                        </div>
                    </div>
                    <div class="form-group mt-3">
                        <label class="control-label">
                            Số điện thoại
                        </label>
                        <div class="controls">
                            @Html.TextBoxFor(model => model.Mobile, new { @class = "form-control", @placeholder = "", @autofocus = "autofocus", disabled = "disabled" })
                        </div>
                    </div>
                    <div class="form-group mt-3">
                        <label class="control-label">
                            Ghi chú
                        </label>
                        <div class="controls">
                            @Html.TextAreaFor(model => model.Note, new { @class = "form-control", @placeholder = "", @autofocus = "autofocus", style = "height:100px;", disabled = "disabled" })
                        </div>
                    </div>
                </div>
            </div>
            <div class="form-actions no-margin">
                <a href="/Admin/ManagerOrder/Index/1" class="btn btn-secondary btn-sm">Quay lại</a>
                @if (Model.Status != CMS.Common.Keywords.DataStatus.Deleted)
                {
                    @Ajax.ActionLink("Hủy đơn hàng", "Delete", new { id = "Details-" + CMS.Common.StringProcess.Encryption.Encode(Model.Id.ToString()) }, new AjaxOptions { Confirm = "Bạn có muốn hủy bản ghi này hay không?", OnComplete = "$('#row_" + Model.Id + "').remove()", HttpMethod = "Delete" }, new { @class = "btn btn-danger btn-sm" })
                }
            </div>
        }
        <div class="clearfix">
        </div>
    </div>
</div>