CMS/CMS/Areas/Admin/Controllers/ConfigController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CMS.Model;
using CMS.Dao;
using CMS.Lib;
using CMS.Common.StringProcess;

namespace CMS.Areas.Admin.Controllers
{
    public class ConfigController: BaseController
    {
        //
        // GET: /Admin/Config/

        public ActionResult Index()
        {
            string order = "4,5,6,7,13,14,12,8,10,11,1,2,3,9";
            string[] list = order.Split(',');
            ConfigDao ConfigLogic = new ConfigDao();
            List<Config_GetByStatus_Result> model = new List<Config_GetByStatus_Result>();
            List<Config_GetByStatus_Result> listItem = new List<Config_GetByStatus_Result>();
            model = ConfigLogic.Config_GetByStatus(CMS.Common.Keywords.DataStatus.Display);
            foreach (var item in list)
            {
                foreach (var i in model)
                {
                    if (item == i.Id.ToString())
                    {
                        listItem.Add(i);
                        break;
                    }
                }
            }
            ViewBag.PanelTitle = ViewBag.Title = "Danh sách các thiết lập hệ thống";
            return View("Index", listItem);
        }

        //
        // GET: /Admin/Config/Details/5

        public ActionResult Details(int id)
        {
            return View();
        }

        //
        // GET: /Admin/Config/Create

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /Admin/Config/Create

        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /Admin/Config/Edit/5

        public ActionResult Edit(string id)
        {
            id = Encryption.Decode(id);
            try
            {
                ConfigDao ConfigLogic = new ConfigDao();
                Config item = new Config();
                item = ConfigLogic.Configs_ViewDetail(Convert.ToInt32(id));
                ViewBag.PanelTitle = ViewBag.Title = "Cập nhật thông tin thiết lập hệ thống: " + item.Name;
                ViewBag.Id = id;
                return View(item);
            }
            catch (Exception)
            {
                return Redirect("/Admin/Config/Index");
            }
        }

        //
        // POST: /Admin/Config/Edit/5

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Edit(string id, FormCollection collection, Config item)
        {
            ViewBag.PanelTitle = ViewBag.Title = "Cập nhật thông tin thiết lập hệ thống: " + item.Name;
            try
            {
                // TODO: Add insert logic here
                //string errorMess = "";
                //if (item.Content == "" || item.Content == null)
                //{
                //    errorMess += "Nội dung của thiết lập không được để trống! ";
                //}
                //if (errorMess != "")
                //{
                //    SetAlert(errorMess, "alert-danger");
                //    return View();
                //}

                ConfigDao ConfigLogic = new ConfigDao();
                item.Id = Convert.ToInt32(Encryption.Decode(id));
                ConfigLogic.Configs_Update(item);
                #region Insert history
                HistoryDao HistoryDaoLogic = new HistoryDao();
                int loginId = Convert.ToInt32(CMS.Common.StringProcess.Encryption.Decode(Request.Cookies[CMS.Common.Keywords.SystemSession.accountLoggedIn].Value));
                HistoryDaoLogic.Insert(loginId, string.Format("Cập nhật thông tin thiết lập hệ thống. Name: {0}", item.Name));
                #endregion
                SetAlert("Cập nhật thành công thiết lập hệ thống!", "alert-success");
                return Redirect("/Admin/Config/Index");
            }
            catch (Exception ex)
            {
                SetAlert("Lỗi " + ex, "alert-danger");
                return View();
            }
        }

        //
        // GET: /Admin/Config/Delete/5

        public ActionResult Delete(int id)
        {
            return View();
        }

        //
        // POST: /Admin/Config/Delete/5

        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

CMS/CMS/Areas/Admin/Views/Config/Edit.cshtml
@model CMS.Model.Config
@{
    Layout = "~/Areas/Admin/Views/Shared/_Layouts.cshtml";
}

@if (ViewBag.Id == "1" || ViewBag.Id == "2" || ViewBag.Id == "3" || ViewBag.Id == "9")
{
    @section ScriptsBottom {
    <script src="/Areas/Admin/ckfinder/ckfinder.js"></script>
    <script src="~/Areas/Admin/ckeditor/ckeditor.js"></script>
    <script src="/Areas/Admin/ckeditor/adapters/jquery.js"></script>
    <script src="/Areas/Admin/ckeditor/config.js"></script>
    <script>
        $(document).ready(function () {
            // Create the editor
            CKEDITOR.replace('Content', {
                language: 'vi',
                height: '500px',
                filebrowserBrowseUrl: '/ExplorerImage/cke/',
                filebrowserUploadUrl: '/ExplorerImage/cke/',
                filebrowserImageBrowseUrl: '/ExplorerImage/cke/'
            });
        });
    </script>
    }
}

<div class="card">
    <div class="card-body">
        @using (Html.BeginForm("Edit", "Config", FormMethod.Post))
        {
            @Html.AntiForgeryToken()
            @Html.ValidationSummary(true)
            if (ViewBag.Id == "4" || ViewBag.Id == "5" || ViewBag.Id == "6" || ViewBag.Id == "7"
                 || ViewBag.Id == "8" || ViewBag.Id == "10" || ViewBag.Id == "14")
            {
                <div class="form-group mt-3">
                    <label>
                        Nội dung
                    </label>
                    <div class="controls">
                        @Html.TextBoxFor(model => model.Content, new { @class = "form-control", @placeholder = "Nội dung", @autofocus = "autofocus" })
                    </div>
                </div>
            }
            else if (ViewBag.Id == "12" || ViewBag.Id == "13")
            {
                <div class="form-group mt-3">
                    <label>
                        Hình ảnh
                    </label>
                    <div class="controls">
                        @Html.TextBoxFor(model => model.Content, new { @class = "form-control", @placeholder = "Hình ảnh", @autofocus = "autofocus", @readonly = "readonly", @style="width: 60%;float:left;" })
                        <span class="help-inline " style="color:red;">
                            *
                        </span>
                        <a onclick="openPopupWindowImage('Content')" class="btn btn-info">Chọn hình ảnh</a>
                    </div>
                </div>
            }

            else if (ViewBag.Id == "11")
            {
                <div class="form-group mt-3">
                    <label>
                        Nội dung
                    </label>
                    <div class="controls">
                        @Html.TextAreaFor(model => model.Content, new { @class = "form-control", @placeholder = "Nội dung", @autofocus = "autofocus", @style = "height:100px;" })
                    </div>
                </div>
            }
            else
            {
            <div class="form-group mt-3">
                <label>
                    Nội dung
                </label>
                <div class="controls">
                    @Html.TextAreaFor(model => model.Content, new { @class = "form-control", @placeholder = "", @autofocus = "autofocus", @style = "height:500px;" })
                </div>
            </div>
            }
            <div class="form-actions no-margin">
                <a href="/Admin/Config/Index" class="btn btn-secondary btn-sm">Hủy</a>
                <button type="submit" class="btn btn-success btn-sm text-white">Cập nhật</button>
            </div>
        }
        <div class="clearfix">
        </div>
    </div>
</div>

CMS/CMS/Areas/Admin/Views/Config/Index.cshtml
@model List<CMS.Model.Config_GetByStatus_Result>
@{
    Layout = "~/Areas/Admin/Views/Shared/_Layouts.cshtml";
}

<div class="row-fluid card">
    <div class="col-md-12">
        <div class="widget">
            <div class="widget-body">
                <table class="table table-condensed table-striped table-bordered table-hover no-margin">
                    <tr>
                        <th>Mã bản ghi</th>
                        <th>Tên thiết lập</th>
                        <th>Chức năng</th>
                    </tr>
                    @for (int i = 0; i < Model.Count; i++)
                    {
                        var item = Model[i];
                        <tr id="row_@item.Id">
                            <td>@item.Id</td>
                            <td>@item.Name</td>
                            <td>
                                <div class="btn-group">
                                    <button type="button" class="btn btn-danger btn-sm text-white dropdown-toggle" data-bs-toggle="dropdown" aria-haspopup="true"aria-expanded="false">
                                        Action
                                        <span class="caret"></span>
                                    </button>
                                    <div class="dropdown-menu">
                                        <a class="dropdown-item" href='/Admin/Config/Edit/@CMS.Common.StringProcess.Encryption.Encode(item.Id.ToString())'>Sửa</a>
                                    </div>
                                </div>
                            </td>
                        </tr>
                    }
                </table>
            </div>
        </div>
    </div>
</div>