CMS/CMS/Areas/Admin/Controllers/ManagerPriceBoardController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CMS.Model;
using CMS.Dao;
using CMS.Lib;
using CMS.Common.StringProcess;

namespace CMS.Areas.Admin.Controllers
{
    public class ManagerPriceBoardController : BaseController
    {
        //
        // GET: /Admin/ManagerPriceBoard/

        public ActionResult Index()
        {
            PriceBoardDao logic = new PriceBoardDao();
            List<PriceBoard_GetByStatus_Result> model = new List<PriceBoard_GetByStatus_Result>();
            model = logic.PriceBoard_GetByStatus(CMS.Common.Keywords.DataStatus.Display).OrderBy(a => a.Value01).ToList();
            ViewBag.PanelTitle = ViewBag.Title = "Bảng giá";
            return View("Index", model);
        }

        //
        // GET: /Admin/ManagerPriceBoard/Details/5

        public ActionResult Details(int id)
        {
            return View();
        }

        //
        // GET: /Admin/ManagerPriceBoard/Create

        public ActionResult Create()
        {
            ViewBag.PanelTitle = ViewBag.Title = "Thêm mới bảng giá";
            ViewBag.Value01 = new SelectList(BindListOrder(), "Value", "Text");
            PriceBoard item = new PriceBoard();
            item.TotalTimeStart = 0;
            item.TotalTimeEnd = 0;
            item.Price = 0;
            return View(item);
        }

        //
        // POST: /Admin/ManagerPriceBoard/Create

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Create(PriceBoard item)
        {
            ViewBag.PanelTitle = ViewBag.Title = "Thêm mới bảng giá";
            ViewBag.Value01 = new SelectList(BindListOrder(), "Value", "Text");
            try
            {
                // TODO: Add insert logic here
                string errorMess = "";

                if (item.TotalTimeStart == null)
                {
                    errorMess += "Thời gian bắt đầu không được để trống! ";
                }
                if (item.TotalTimeEnd == null)
                {
                    errorMess += "Thời gian kết thúc không được để trống! ";
                }
                if (errorMess != "")
                {
                    SetAlert(errorMess, "alert-danger");
                    return View();
                }
                PriceBoardDao logic = new PriceBoardDao();
                item.Status = 1;
                logic.PriceBoard_Insert(item);
                #region Insert history
                HistoryDao HistoryDaoLogic = new HistoryDao();
                int loginId = Convert.ToInt32(CMS.Common.StringProcess.Encryption.Decode(Request.Cookies[CMS.Common.Keywords.SystemSession.accountLoggedIn].Value));
                HistoryDaoLogic.Insert(loginId, string.Format("Thêm mới bảng giá. {0} - {1}: {2} VNĐ", item.TotalTimeStart, item.TotalTimeEnd, item.Price));
                #endregion
                SetAlert("Thêm mới thành công!", "alert-success");
                return Redirect("/Admin/ManagerPriceBoard/Index/");
            }
            catch (Exception ex)
            {
                SetAlert("Lỗi " + ex, "alert-danger");
                return View();
            }
        }

        //
        // GET: /Admin/ManagerPriceBoard/Edit/5

        public ActionResult Edit(string id)
        {
            id = Encryption.Decode(id);
            try
            {
                PriceBoardDao logic = new PriceBoardDao();
                PriceBoard item = new PriceBoard();
                item = logic.PriceBoard_ViewDetail(Convert.ToInt32(id));
                ViewBag.PanelTitle = ViewBag.Title = "Cập nhật thông tin bảng giá";
                ViewBag.Value01 = new SelectList(BindListOrder(), "Value", "Text", item.Value01);
                return View(item);
            }
            catch (Exception)
            {
                return Redirect("/Admin/ManagerPriceBoard/Index/");
            }
        }

        //
        // POST: /Admin/ManagerPriceBoard/Edit/5

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Edit(string id, PriceBoard item)
        {
            ViewBag.PanelTitle = ViewBag.Title = "Cập nhật thông tin bảng giá";
            ViewBag.Value01 = new SelectList(BindListOrder(), "Value", "Text", item.Value01);
            try
            {
                // TODO: Add insert logic here
                string errorMess = "";
                if (item.TotalTimeStart == null)
                {
                    errorMess += "Thời gian bắt đầu không được để trống! ";
                }
                if (item.TotalTimeEnd == null)
                {
                    errorMess += "Thời gian kết thúc không được để trống! ";
                }
                if (errorMess != "")
                {
                    SetAlert(errorMess, "alert-danger");
                    return View();
                }
                PriceBoardDao logic = new PriceBoardDao();
                item.Id = Convert.ToInt32(Encryption.Decode(id));
                logic.PriceBoard_UpdateInfor(item);
                #region Insert history
                HistoryDao HistoryDaoLogic = new HistoryDao();
                int loginId = Convert.ToInt32(CMS.Common.StringProcess.Encryption.Decode(Request.Cookies[CMS.Common.Keywords.SystemSession.accountLoggedIn].Value));
                HistoryDaoLogic.Insert(loginId, string.Format("Cập nhật thông tin bảng giá. {0} - {1}: {2} VNĐ", item.TotalTimeStart, item.TotalTimeEnd, item.Price));
                #endregion
                SetAlert("Cập nhật thành công!", "alert-success");
                return Redirect("/Admin/ManagerPriceBoard/Index/");
            }
            catch (Exception ex)
            {
                SetAlert("Lỗi " + ex, "alert-danger");
                return View();
            }
        }

        //
        // GET: /Admin/ManagerPriceBoard/Delete/5

        public ActionResult Delete(int id)
        {
            try
            {
                PriceBoardDao logic = new PriceBoardDao();
                PriceBoard item = new PriceBoard();
                item = logic.PriceBoard_ViewDetail(id);
                logic.PriceBoard_UpdateStatus(id, CMS.Common.Keywords.DataStatus.Deleted);
                #region Insert history
                HistoryDao HistoryDaoLogic = new HistoryDao();
                int loginId = Convert.ToInt32(CMS.Common.StringProcess.Encryption.Decode(Request.Cookies[CMS.Common.Keywords.SystemSession.accountLoggedIn].Value));
                HistoryDaoLogic.Insert(loginId, string.Format("Xóa bảng giá. {0} - {1}: {2} VNĐ", item.TotalTimeStart, item.TotalTimeEnd, item.Price));
                #endregion
                SetAlert("Xóa thành công!", "alert-success");
                return Redirect("/Admin/ManagerPriceBoard/Index/");
            }
            catch (Exception ex)
            {
                SetAlert("Lỗi " + ex, "alert-danger");
                return View();
            }
        }

        //
        // POST: /Admin/ManagerPriceBoard/Delete/5

        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
        public List<SelectListItem> BindListOrder()
        {
            List<SelectListItem> listItems = new List<SelectListItem>();
            for (int i = 1; i < 21; i++)
            {
                listItems.Add(new SelectListItem { Text = i.ToString(), Value = i.ToString() });
            }
            return listItems;
        }
    }
}

CMS/CMS/Areas/Admin/Views/ManagerPriceBoard/Create.cshtml
@model CMS.Model.PriceBoard
@{
    Layout = "~/Areas/Admin/Views/Shared/_Layouts.cshtml";
}
<div class="card">
    <div class="card-body">
        @using (Html.BeginForm("Create", "ManagerPriceBoard", FormMethod.Post))
        {
            @Html.AntiForgeryToken()
            @Html.ValidationSummary(true)
            <div class="col-sm-7 form-control-span">
                <div class="col-sm-12 form-control-span-main">
                    <div class="form-group mt-3">
                        <label class="control-label">
                            Thời gian bắt đầu
                            <span class="help-inline " style="color:red;">*</span>
                        </label>
                        <div class="controls">
                            @Html.TextBoxFor(model => model.TotalTimeStart, new { @class = "form-control", @placeholder = "", @autofocus = "autofocus", type = "number", min = "0", step="0.1" })
                        </div>
                    </div>
                    <div class="form-group mt-3">
                        <label class="control-label">
                            Thời gian kết thúc
                            <span class="help-inline " style="color:red;">*</span>
                        </label>
                        <div class="controls">
                            @Html.TextBoxFor(model => model.TotalTimeEnd, new { @class = "form-control", @placeholder = "", @autofocus = "autofocus", type = "number", min = "0", step = "0.1" })
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-sm-5 form-control-span">
                <div class="col-sm-12 form-control-span-main">
                    <div class="form-group mt-3">
                        <label class="control-label">
                            Giá
                        </label>
                        <div class="controls">
                            @Html.TextBoxFor(model => model.Price, new { @class = "form-control", @placeholder = "", @autofocus = "autofocus", type = "number", min = "0" })
                        </div>
                    </div>
                    <div class="form-group mt-3">
                        <label class="control-label">
                            Thứ tự hiển thị
                        </label>
                        <div class="controls">
                            @Html.DropDownListFor(model => model.Value01, null, new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.Value01)
                        </div>
                    </div>
                </div>
            </div>
            <div class="form-actions no-margin">
                <a href="/Admin/ManagerPriceBoard/Index/" class="btn btn-secondary btn-sm">Hủy</a>
                <button type="submit" class="btn btn-success btn-sm text-white">Thêm mới</button>
            </div>
        }
        <div class="clearfix">
        </div>
    </div>
</div>

CMS/CMS/Areas/Admin/Views/ManagerPriceBoard/Edit.cshtml
@model CMS.Model.PriceBoard
@{
    Layout = "~/Areas/Admin/Views/Shared/_Layouts.cshtml";
}
<div class="card">
    <div class="card-body">
        @using (Html.BeginForm("Edit", "ManagerPriceBoard", FormMethod.Post))
        {
            @Html.AntiForgeryToken()
            @Html.ValidationSummary(true)
            <div class="col-sm-7 form-control-span">
                <div class="col-sm-12 form-control-span-main">
                    <div class="form-group mt-3">
                        <label class="control-label">
                            Thời gian bắt đầu
                            <span class="help-inline " style="color:red;">*</span>
                        </label>
                        <div class="controls">
                            @Html.TextBoxFor(model => model.TotalTimeStart, new { @class = "form-control", @placeholder = "", @autofocus = "autofocus", type = "number", min = "0", step = "0.1" })
                        </div>
                    </div>
                    <div class="form-group mt-3">
                        <label class="control-label">
                            Thời gian kết thúc
                            <span class="help-inline " style="color:red;">*</span>
                        </label>
                        <div class="controls">
                            @Html.TextBoxFor(model => model.TotalTimeEnd, new { @class = "form-control", @placeholder = "", @autofocus = "autofocus", type = "number", min = "0", step = "0.1" })
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-sm-5 form-control-span">
                <div class="col-sm-12 form-control-span-main">
                    <div class="form-group mt-3">
                        <label class="control-label">
                            Giá
                        </label>
                        <div class="controls">
                            @Html.TextBoxFor(model => model.Price, new { @class = "form-control", @placeholder = "", @autofocus = "autofocus", type = "number", min = "0" })
                        </div>
                    </div>
                    <div class="form-group mt-3">
                        <label class="control-label">
                            Thứ tự hiển thị
                        </label>
                        <div class="controls">
                            @Html.DropDownListFor(model => model.Value01, null, new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.Value01)
                        </div>
                    </div>
                </div>
            </div>
            <div class="form-actions no-margin">
                <a href="/Admin/ManagerPriceBoard/Index/" class="btn btn-secondary btn-sm">Hủy</a>
                <button type="submit" class="btn btn-success btn-sm text-white">Cập nhật</button>
            </div>
        }
        <div class="clearfix">
        </div>
    </div>
</div>

CMS/CMS/Areas/Admin/Views/ManagerPriceBoard/Index.cshtml
@model List<CMS.Model.PriceBoard_GetByStatus_Result>
@{
    Layout = "~/Areas/Admin/Views/Shared/_Layouts.cshtml";
}
@section ButtomRight {
    <div class="ms-auto text-end">
        <a href="/Admin/ManagerPriceBoard/Create" title="Thêm mới thẻ" class="btn btn-info btn-sm">
            <span class="fas fa-plus"></span> Thêm mới
        </a>
    </div>
}
<div class="row-fluid card">
    <div class="col-md-12">
        <div class="widget">
            <div class="widget-body">
                <table class="table table-condensed table-striped table-bordered table-hover no-margin">
                    <tr>
                        <th>Thời gian</th>
                        <th>Giá</th>
                        <th>Ghi chú</th>
                        <th>Chức năng</th>
                    </tr>
                    @for (int i = 0; i < Model.Count; i++)
                    {
                        var item = Model[i];
                        <tr id="row_@item.Id">
                            <td>Từ @(item.TotalTimeStart)h đến @(item.TotalTimeEnd)h</td>
                            <td>@(String.Format("{0:0,0}", Convert.ToDecimal(item.Price)))đ</td>
                            <td>@item.Note</td>
                            <td>
                                <div class="btn-group">
                                    <button type="button" class="btn btn-danger btn-sm text-white dropdown-toggle" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        Action
                                        <span class="caret"></span>
                                    </button>
                                    <div class="dropdown-menu">
                                        <a class="dropdown-item" href='/Admin/ManagerPriceBoard/Edit/@CMS.Common.StringProcess.Encryption.Encode(item.Id.ToString())'>Sửa</a>
                                        @Ajax.ActionLink("Xóa", "Delete", new { @id = @item.Id }, new AjaxOptions { Confirm = "Bạn có muốn xóa bản ghi này hay không?", OnComplete = "$('#row_" + item.Id + "').remove()", HttpMethod = "Delete" }, new { @class = "dropdown-item" })
                                    </div>
                                </div>
                            </td>
                        </tr>
                    }
                </table>
            </div>
        </div>
    </div>
</div>